### ISSUE TITLE
Packagist support

### ISSUE THREAD

**Issue by vincentchalamon** [LancasterSolutions/mindbaz-library#1]
Hey,
I'm using this library as a dependency of [MindbazBundle](https://github.com/Kozikaza/MindbazBundle) to provide a SwiftMailer Transport for Symfony. Can you please register this library in [Packagist](https://packagist.org/) in a stable version?
Thanks

**Comment by erfindel** [comment]
Done: https://packagist.org/packages/lancaster-solutions/mindbaz-library
